### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by thecsw** [alexshadley/jammr#1]

**Comment by alexshadley** [comment]
Hey, thanks for your interest! Jammr currently consists of an elm frontend and a quickly hacked-together python backend. Run `backend.py` with python3 and the required dependencies (in requirements.txt), and use your favorite JS dep bundler (I like parcel pretty well) to bundle `index.html`

**Comment by alexshadley** [comment]
I'm also working on deploying the software, hopefully that's available soon

**Comment by alexshadley** [comment]
Demo now available at http://alexshadley.com/jammr
